/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FurnitureService } from "../furniture.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FurnitureCreateInput } from "./FurnitureCreateInput";
import { Furniture } from "./Furniture";
import { FurnitureFindManyArgs } from "./FurnitureFindManyArgs";
import { FurnitureWhereUniqueInput } from "./FurnitureWhereUniqueInput";
import { FurnitureUpdateInput } from "./FurnitureUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FurnitureControllerBase {
  constructor(
    protected readonly service: FurnitureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Furniture })
  @nestAccessControl.UseRoles({
    resource: "Furniture",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFurniture(
    @common.Body() data: FurnitureCreateInput
  ): Promise<Furniture> {
    return await this.service.createFurniture({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        color: true,
        price: true,
        name: true,
        description: true,
        material: true,
        dimensions: true,
        inStock: true,
        category: true,
        materialUsed: true,
        sizeDimensions: true,
        available: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Furniture] })
  @ApiNestedQuery(FurnitureFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Furniture",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async furnitures(@common.Req() request: Request): Promise<Furniture[]> {
    const args = plainToClass(FurnitureFindManyArgs, request.query);
    return this.service.furnitures({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        color: true,
        price: true,
        name: true,
        description: true,
        material: true,
        dimensions: true,
        inStock: true,
        category: true,
        materialUsed: true,
        sizeDimensions: true,
        available: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Furniture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Furniture",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async furniture(
    @common.Param() params: FurnitureWhereUniqueInput
  ): Promise<Furniture | null> {
    const result = await this.service.furniture({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        color: true,
        price: true,
        name: true,
        description: true,
        material: true,
        dimensions: true,
        inStock: true,
        category: true,
        materialUsed: true,
        sizeDimensions: true,
        available: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Furniture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Furniture",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFurniture(
    @common.Param() params: FurnitureWhereUniqueInput,
    @common.Body() data: FurnitureUpdateInput
  ): Promise<Furniture | null> {
    try {
      return await this.service.updateFurniture({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          color: true,
          price: true,
          name: true,
          description: true,
          material: true,
          dimensions: true,
          inStock: true,
          category: true,
          materialUsed: true,
          sizeDimensions: true,
          available: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Furniture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Furniture",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFurniture(
    @common.Param() params: FurnitureWhereUniqueInput
  ): Promise<Furniture | null> {
    try {
      return await this.service.deleteFurniture({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          color: true,
          price: true,
          name: true,
          description: true,
          material: true,
          dimensions: true,
          inStock: true,
          category: true,
          materialUsed: true,
          sizeDimensions: true,
          available: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
